### ISSUE TITLE
[BUG] Unable to find template

### ISSUE THREAD

**Issue by zomars** [ericmorand/gulp-twing#1]
I've setup a [simple repo](https://github.com/zomars/gulp-twing-test) to test the plugin and it seems the plugin is struggling to find relative paths en passing globs from gulp.

This is my log:
```
UnhandledPromiseRejectionWarning: TwingErrorLoader: Unable to find template "/Users/zomars/Sites/gulp-twing-test/src/templates/index.twig" (looked into: ./src/templates).
    at TwingLoaderFilesystem.findTemplate (/Users/zomars/Sites/gulp-twing-test/node_modules/twing/lib/twing/loader/filesystem.js:177:15)
    at TwingLoaderFilesystem.getCacheKey (/Users/zomars/Sites/gulp-twing-test/node_modules/twing/lib/twing/loader/filesystem.js:114:25)
    at TwingEnvironment.getTemplateClass (/Users/zomars/Sites/gulp-twing-test/node_modules/twing/lib/twing/environment.js:204:36)
    at TwingEnvironment.loadTemplate (/Users/zomars/Sites/gulp-twing-test/node_modules/twing/lib/twing/environment.js:268:24)
    at TwingEnvironment.render (/Users/zomars/Sites/gulp-twing-test/node_modules/twing/lib/twing/environment.js:215:27)
    at Transform.stream._transform (/Users/zomars/Sites/gulp-twing-test/node_modules/gulp-twing/src/index.js:23:13)
    at Transform._read (_stream_transform.js:185:10)
    at Transform._write (_stream_transform.js:173:12)
    at doWrite (_stream_writable.js:406:12)
    at writeOrBuffer (_stream_writable.js:392:5)
(node:7996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ericmorand** [comment]
That's the expected behavior and it comes from Twing - and from TwigPHP. Filesystem loader will always look for templates inside one of its configured path. This is different from what Twig.js does for example - and I'm not sure the behavior of Twig.js is a bug or a deliberate move.

I created a PR that add the Partials namespace to the loader and it works.

I clearly don't want to change the filesystem loader behavior in Twing - its behavior is actually the expected one based on Twig specs. But I've been thinking on providing a standalone custom loader in the form of a npm package that would allow for relative path resolving. What do you think?

**Comment by zomars** [comment]
I don't it's necessary to change the loader behavior. I've made some quick fixes that solves this in [this PR](https://github.com/ericmorand/gulp-twing/pull/3/files).

**Comment by ericmorand** [comment]
@zomars , you are totally right, gulp-twing behavior is incorrect from Twing perspective. All templates are resolved from on of the registered path of the filesystem loader and gulp-twing has to respect that.

I pulled your PR and made some changes to strictly respect Twing rules. Templates will now be resolved by gulp-twing relatively to the current working directory and the loader should be registered at least with the current working directory. I'll update the doc accordingly.

Thanks a lot for your inputs and your help.
